import cn from 'classnames'
import parse from 'html-react-parser'
import { createElement } from 'react'

import { Content, useConverterContext } from '../'
import RenderInline from '../RenderInline'
import { type SectionBlock } from '../utils/prepareDocument'

const Section = ({ node }: { node: SectionBlock }) => {
  const { document } = useConverterContext()
  const docAttrs = document.attributes || {}

  const sectNumLevels = docAttrs['sectnumlevels']
    ? parseInt(`${docAttrs['sectnumlevels']}`)
    : 3

  const numbered =
    node.numbered && node.num && node.num !== '.' && node.level <= sectNumLevels && !node.hasCaption
  const titlePrefix = numbered ? `${node.num} ` : ''

  // Captioned titles are asciidoctor HTML strings (the caption prefix is
  // generated by stock); parse them into React nodes. Everything else comes
  // from our own inline AST.
  const titleInner = node.hasCaption ? (
    parse(node.title)
  ) : (
    <>
      {titlePrefix}
      <RenderInline nodes={node.titleInlines} />
    </>
  )

  const hasAnchor = docAttrs['sectanchors'] !== undefined
  const hasLink = docAttrs['sectlinks'] !== undefined

  const titleNode =
    hasLink && node.id ? (
      <a className="link" href={`#${node.id}`}>
        {titleInner}
      </a>
    ) : (
      titleInner
    )

  const headingChildren = (
    <>
      {hasAnchor && node.id && <a className="anchor" href={`#${node.id}`} />}
      {titleNode}
    </>
  )

  const heading = createElement(
    `h${node.level + 1}`,
    {
      id: node.id || undefined,
      ...(node.lineNumber ? { 'data-lineno': node.lineNumber } : {}),
    },
    headingChildren,
  )

  if (node.level === 0) {
    return (
      <>
        {createElement(
          'h1',
          {
            id: node.id || undefined,
            className: cn('sect0', node.role),
            ...(node.lineNumber ? { 'data-lineno': node.lineNumber } : {}),
          },
          headingChildren,
        )}
        <Content blocks={node.blocks} />
      </>
    )
  }

  // sect1 wraps children in `<div class="sectionbody">`; sect2+ render
  // children directly.
  if (node.level === 1) {
    return (
      <div
        className={cn(`sect${node.level}`, node.role)}
        {...(node.lineNumber ? { 'data-lineno': node.lineNumber } : {})}
      >
        {heading}
        <div className="sectionbody">
          <Content blocks={node.blocks} />
        </div>
      </div>
    )
  }

  return (
    <div
      className={cn(`sect${node.level}`, node.role)}
      {...(node.lineNumber ? { 'data-lineno': node.lineNumber } : {})}
    >
      {heading}
      <Content blocks={node.blocks} />
    </div>
  )
}

export default Section
